### ISSUE TITLE
Symptoms checker modal background overlay persists even after completing the test

### ISSUE THREAD

**Issue by kartikcho** [kartik918/world-wont-stop#8]
## Steps to recreate:

- Use "Check Symptoms" button.
- Follow through the test and finish it.
- On completion, the browser window closes but the overlay persists.

## Possible solution:

On clicking the "Check Symptoms" button again, the overlay seems to go away so maybe fire the toggle button on modal close so the overlay goes away.

**Comment by palak-sethi** [comment]
I'd like to work on this

**Comment by kartikcho** [comment]
Okay assigning this to you.
